name: Bundle Stats

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  bundle-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          cache: npm
          node-version: 24.21.0

      - run: npm ci

      - name: Bundle Stats
        uses: rexxars/bundle-stats@c8bb783559da734cbb251f66731ee5227ba41059 # v2.0.1
        with:
          build-command: "npm run build"
